name: Azure WebApp
on:
  push:
    branches:
    - release
jobs:
  deploy:
    name: deploy website
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: release
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploying web app to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: bloodplus
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
          package: bloodplus/app