name: Azure WebApp
on:
  push:
    branches:
    - release
jobs:
  deploy:
    name: deploy website
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: release

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o 'bloodplus/app'

      - name: Deploying web app to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: bloodplus
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
          package: bloodplus/app