name: Azure WebApp
on:
  push:
    branches:
    - release
jobs:
  deploy:
    name: deploy release
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@release

      - name: Deploying web app to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: bloodplus
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
          package: bloodplus/app